### ISSUE TITLE
Target .NET Standard instead of .NET Framework

### ISSUE THREAD

**Issue by Fs00** [MarcolinoPT/Xunit.Repeat#2]
Thanks for making this simple but effective package! I've found it very useful in one of my projects.
I have only a small improvement to ask for. Since I'm using this package in a .NET Core application, every time I do a project restore I get warning NU1701, which says that the package was restored with a different framework than the one the project targets.
This doesn't cause any problems on Windows since .NET Framework is pre-installed, but on a cross-platform environment things would get more problematic.
That's why I ask you to update your package to target .NET Standard 2.0 (like xUnit does) instead of .NET Framework, in order to make it fully compatible with all .NET platforms.
Thanks in advance!

**Comment by MarcolinoPT** [comment]
Hi, @Fs00 thanks for using the package. It was born out of necessity while working for a customer. If you need an alternative in .NET Standard you can use the forked version of this project.
I will submit a new version in .NET Standard as soon as possible 😄

**Comment by MarcolinoPT** [comment]
New package submitted

**Comment by Fs00** [comment]
Thanks!🎉
